// Give file location in relation to the importing file, and you can omit file extension
import Note from './components/Note'

/* Move Note into its own component file 
const Note = ({ note }) => {
  return (
    <li>{note.content}</li>
  )
}
*/

/* When we create a new component for Notes, the key has to be defined on the component itself */
const App = ({ notes }) => {
  return (
    <div>
      <h1>Notes</h1>
      <ul>
        {notes.map(note => 
          <Note key={note.id} note={note} />
        )}
      </ul>
    </div>
  )
}

/*
const App = ({ notes }) => {

  return (
    <div>
      <h1>Notes</h1>
      <ul>
        { This works, but isn't practical if we expand the array of notes }
         <li>{notes[0].content}</li>
        <li>{notes[1].content}</li>
        <li>{notes[2].content}</li>
        
        { notes.map(note =>
            React needs "key" attributes for the objects (elements) generated by map(). 
            React uses key attributes  to determine how to update the view generated by a component 
            when the component is re-rendered. 
            
            Also, don't forget the curly braces - you'll get errors if you do not include them.
          <li key={note.id}>
            {note.content}
          </li>
        ) }
      </ul>
    </div>
  )
}
*/


export default App